jdwilkin4/fcc-forum-clone

- CODE_OF_CONDUCT.md
I don't see the difference between this project and the contrast ratio one in terms of code of conduct.
So I just shamelessly copy-pasted the example from the contrast ratio project. Seems like cheating, but also logical.
Fixes #5
> Chore: added code of conduct

- README.md
Side question: what is the purpose of this comments in README:
``
Fixes #3
> docs: Added description to the README file

- constants.js
- index.js
> chore: Added URL constants

- styles.css
I am not sure if I named variables good enough. This color-naming thing is somewhat confusing.
Fixes #10
> chore: Add color variables and category classes in CSS file

- index.html
- index.js
Made changes as requested
Fixes #8
> Chore: add year to the footer

- helpers.js
- index.js
> Chore: added-categories-obj

- index.html
- styles.css
Added `<main>` and `<h1>` elements with required content and styling.
Updated `<body>` styling.
Fixes [#7](https://github.com/jdwilkin4/fcc-forum-clone/issues/7#issue-1368515107)
> style: added bgcolor, font and h1

- README.md
My suggestion for the README file.
Fixes #32
> docs: changed structure of the README

- CONTRIBUTING.md
Used file from contrast-ratio-app as a template, but added/restructured some things.
So in README we have somewhat consice contributing instructions.
In this file, there is little more detailed explanation.
Fixes #4
> docs: Added contributing guide

- CONTRIBUTING.md
Added a table of contents to the contributing file.
Fixes #36
> chore: add a table of contents to CONTRIBUTING file

- index.html
- styles.css
I have added the table headers from forum Post as depicted in the figma file.  The headers are styled and made responsive to the best of my abilities.  
Fixes #9
> table-headers-and-style-added

- index.html
- index.js
`<tbody>` element is added with id in html file. The id can be accessed through a variable in js file. 
Fixes #11
> added-empty-table-body

- index.js
Basic setup with Fetch API to `fetch` latest FCC forum data.
- variables initialised with default states
- if response status OK, extract data, otherwise throw an error
- variables modified according to the result
- result and data print to the console
Fixes #14
> feat: forum fetch setup

- index.js
- styles.css
Added `displaySummary` inside the `displayTopic` function which displays the post's summary if any included.
Fixes #20
> feat: add summary to forum post (#20)

- index.js
Modified naming of functions and variables that have the word topic to post.
Fixes #45
> chore: naming modifications

- constants.js
- index.html
- index.js
- styles.css
Display posters avatars for each of the forum posts. 
Fixes #21
> feat: add forum user avatars

- index.js
Fixes #22 - As discussed in the discord I tried to implement the post counts into the td but I haven't found the correct solution. Solution 1 shows all the values in each post replies section.  I thought about using Solution 2 to match the title to post.title and presenting the values like that but I've been unable to do so.
- [x ] New feature (non-breaking change which adds functionality)
> feat: add forum replies #22

- index.html
- styles.css
Made changes for table header in index.html and index.css as per issue number 54. 
Fixes #54
> changed header for issue 54

- index.html
- index.js
- styles.css
Adding functions for sort buttons
Fixes #56
> Working on  issue 56

- helpers.js
- index.html
- index.js
- styles.css
Added filter buttons as requested in the issue. No styling.
Fixes #57
> #57 add filter buttons

- index.html
> Chore: added cdn for FontAwesome library

- index.html
- index.js
- styles.css
I think I resolved the layout shift issue of the footer. Thanks for the helpful hints. I didn't really get the `index.js` code but with the help I was able to know where to implement the change in the code.
Fixes #63
> worked-on-issue-63 

- index.js
Removed the `displayPosterAvatar` function to integrate the newly created `getUserAvatarComponent` inside the `displayPost`.
Fixes #71
> #71 Preparation for creating the list of users

- index.html
- index.js
- styles.css
Added the list of users, included the shrinking/expanding transitions as well.
Fixes #72
> #72 Add the list of users

- index.js
added filtering ability to handleClickFilter
Fixes #59
> feature: add filtering ability

- index.js
> Accesing object properties inconsistency fixed

- index.js
> feature: filter and sort

- index.html
- styles.css
Did styling of buttons , and fixed the container issue of aligning to left , 
Fixes #81 
made a 'reset' class to fix the container aligining issue , and designed buttons after selecting them by '#filter-btns button'...
> Fix alignment of the #filter-btns

- index.js
refresh the page and content every 30 secs
Fixes # 87
> feature: refresh the page every 30 seconds
